kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ((cluster-role-name))
# rules:
# - apiGroups: [""]
#   resources: ["*.*"]
#   verbs: ["get", "watch", "list", "create", "update"]
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
