kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ((rolename))-binding
  namespace: ((namespace))
subjects:
- kind: User
  name: ((username))
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ((rolename))
  apiGroup: rbac.authorization.k8s.io
