---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ((rolename))
  namespace: ((namespace))
# rules:
# - apiGroups: [""]
#   resources: ["*.*"]
#   verbs: ["get", "watch", "list", "create", "update"]
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
